#!/bin/sh

set +x

# parameter1 docker1
# parameter2 docker2
# parameter3 file

if [ $# -ne 3 ]; then
    echo "USAGE: riscv-compiler docker1 docker2 file.c"
    echo "       docker1: name of container1"
    echo "       docker2: name of container2"
    echo "       file.c : path of file to compile"
    exit 1
fi

if [[ $3 == *.c ]]; then
    RISCV_COMPILER="riscv-cc"
else
    RISCV_COMPILER="riscv-cxx"
fi

docker cp $3 $1:/$3

docker exec -i $1 bash -c "$RISCV_COMPILER $3 -o riscv.out"
docker cp $1:/riscv.out /tmp/riscv.out
docker cp /tmp/riscv.out $2:/root/riscv.out
docker exec -i $2 bash -c "cat /root/riscv.out | sshpass -p \"busybear\" ssh root@172.17.0.3 \"cat > /root/riscv.out\""
docker exec -i $2 bash -c "sshpass -p \"busybear\" ssh root@172.17.0.3 \"chmod a+x /root/riscv.out && /root/riscv.out\""
